### ISSUE TITLE
Filter rules by tags - exclusion

### ISSUE THREAD

**Issue by security-intel** [3c7/yaramanager#3]
Hello @3c7 - I wanted to apply some extra filtering conditions using a SQLAlchemy query, but didn't succeeded yet. [Here](https://stackoverflow.com/questions/69483785/sqlalchemy-apply-filter-before-join-statement) is a question where i described most of the issue, and I was wondering if you may have a better idea maybe? Much appreciated. Thanks

**Comment by 3c7** [comment]
To be honest, I have thought about that, too, and didn't come up with a solution, because I had the same issue. Will think about that!

**Comment by 3c7** [comment]
Haven't found a quick solution. Iterating over the tags after retrieving the rules from the DB is possible, but seems not to be very elegant. But it works...

**Comment by security-intel** [comment]
What about this one?

```
rules = rules.select_from(Tag).join(Rule.tags).filter(~Rule.id.in_(
            rules.select_from(Tag).join(Rule.tags).filter(Tag.name.in_(tags)).with_entities(Rule.id)
))
```
Is not that elegant, but is sql(ish)

**Comment by 3c7** [comment]
Thanks, good idea!
